version: '3.9'

services:
  database_kilometer_tracker:
    container_name: db_postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=etros_kilometer_tracker
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: kilometer_tracker
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
      - /usr/src/node_modules
    links:
      - database_kilometer_tracker
    depends_on:
      - database_kilometer_tracker

volumes:
  pgdata:
    driver: local
